/**
 * Document ingestion: converts everything in docs/ (PDF, DOCX, TXT, MD)
 * into a single knowledge/knowledge.md file that the chatbot loads as its
 * grounded reference material.
 *
 * Usage:  npm run ingest
 * Re-run it every time you add, update, or remove a document, then redeploy.
 */
import fs from "node:fs/promises";
import path from "node:path";
import { createRequire } from "node:module";
import mammoth from "mammoth";

// pdf-parse's index.js has a debug-mode bug when imported directly; load the lib.
const require = createRequire(import.meta.url);
const pdfParse = require("pdf-parse/lib/pdf-parse.js");

const DOCS_DIR = path.resolve("docs");
const OUT_FILE = path.resolve("knowledge", "knowledge.md");

const SUPPORTED = new Set([".pdf", ".docx", ".txt", ".md"]);

async function extractText(filePath) {
  const ext = path.extname(filePath).toLowerCase();
  if (ext === ".pdf") {
    const data = await pdfParse(await fs.readFile(filePath));
    return data.text;
  }
  if (ext === ".docx") {
    const result = await mammoth.extractRawText({ buffer: await fs.readFile(filePath) });
    return result.value;
  }
  // .txt / .md
  return fs.readFile(filePath, "utf8");
}

function cleanup(text) {
  return text
    .replace(/\r\n/g, "\n")
    .replace(/[ \t]+\n/g, "\n")
    .replace(/\n{4,}/g, "\n\n\n")
    .trim();
}

async function main() {
  let entries;
  try {
    entries = await fs.readdir(DOCS_DIR, { withFileTypes: true });
  } catch {
    console.error(`No docs/ folder found at ${DOCS_DIR}. Create it and add your PDFs/DOCX/TXT files.`);
    process.exit(1);
  }

  const files = entries
    .filter((e) => e.isFile() && SUPPORTED.has(path.extname(e.name).toLowerCase()))
    .map((e) => e.name)
    .sort();

  if (files.length === 0) {
    console.error("docs/ contains no supported files (.pdf, .docx, .txt, .md). Nothing to ingest.");
    process.exit(1);
  }

  const sections = [];
  for (const name of files) {
    process.stdout.write(`Ingesting ${name} ... `);
    try {
      const raw = await extractText(path.join(DOCS_DIR, name));
      const text = cleanup(raw);
      if (!text) {
        console.log("SKIPPED (no extractable text — is it a scanned image PDF?)");
        continue;
      }
      sections.push(`<document title="${name}">\n${text}\n</document>`);
      console.log(`ok (${text.length.toLocaleString()} chars)`);
    } catch (err) {
      console.log(`FAILED: ${err.message}`);
    }
  }

  if (sections.length === 0) {
    console.error("No documents produced text. Aborting without writing knowledge.md.");
    process.exit(1);
  }

  const banner =
    "<!-- GENERATED by scripts/ingest.mjs — do not edit by hand. " +
    `Built ${new Date().toISOString()} from ${sections.length} document(s). -->\n\n`;
  const body = sections.join("\n\n");

  await fs.mkdir(path.dirname(OUT_FILE), { recursive: true });
  await fs.writeFile(OUT_FILE, banner + body, "utf8");

  const totalChars = body.length;
  const approxTokens = Math.round(totalChars / 4); // rough heuristic for sizing only
  console.log(`\nWrote ${OUT_FILE}`);
  console.log(`Total: ${totalChars.toLocaleString()} chars (~${approxTokens.toLocaleString()} tokens, rough estimate).`);
  if (approxTokens > 150000) {
    console.warn(
      "\nWARNING: knowledge base is getting large (>~150K tokens). " +
        "Responses will still work but cost more per question. " +
        "See README section 'When to switch to a vector database'."
    );
  }
  console.log("\nNext: commit the change and redeploy (git add -A && git commit -m 'update docs' && git push).");
}

main();
